export enum ToolCapabilities {
  FILE_READ = 'file:read',
  FILE_WRITE = 'file:write',
  FILE_EDIT = 'file:edit',
  FILE_DELETE = 'file:delete',
  COMMAND_EXECUTION = 'command:execute',
  BROWSER_NAVIGATE = 'browser:navigate',
  BROWSER_INTERACT = 'browser:interact',
  WEB_FETCH = 'web:fetch',
  WEB_SEARCH = 'web:search',
  NETWORK = 'network',
  TOOL_MANAGEMENT = 'tool:management',
  TASK_MANAGEMENT = 'task:management',
  AGENT_SPAWN = 'agent:spawn',
  MCP_ACCESS = 'mcp:access',
  SKILL_EXECUTION = 'skill:execute',
  PERMISSION_MANAGEMENT = 'permission:management',
}
